### PR TITLE
Update xml_config.conf

### PR DESCRIPTION
**Pull request by aashishchauhan06**

### CODE REVIEW

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
Rishabh

**Comment by aashishchauhan06** [comment]
\review

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - We encountered technical difficulties while attempting to generate code feedback. Please try again or contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - We encountered technical difficulties while attempting to generate code feedback. Please try again or contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - We encountered technical difficulties while attempting to generate code feedback. Please try again or contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - Whoops! The AI Code Review Agent did not run because provided file & folder exclusion pattern excluded all files in PR. Please contact support@bito.ai to change this.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - We encountered technical difficulties while attempting to generate code feedback. Please try again or contact support@bito.ai.

**Comment by aashish-chauhan-bito** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** ❌Failure - We encountered technical difficulties while attempting to generate code feedback. Please try again or contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
## Code Review Agent Run Status

- **Limitations and other issues:** Code Review session failed. Please contact support@bito.ai.

**Comment by aashishchauhan06** [comment]
review #exclude_files=

**Comment by aashishchauhan06** [comment]
<div>
<h2>Code Review Agent Run #6c9fa9</h2>
<div>
<ul>

</ul>
</div>
<div>
<h3>Code Review Overview</h3>
<ul>
<li><b>Summary</b>: The pull request includes significant configuration changes in 'xml_config.conf', enhancing the file's capacity and improving Elasticsearch's data handling by adding a new node and index.</li>
<li><b>Files</b>: 1</li>
<li><b>Issue found</b>: Total - 0, High importance - 0 &nbsp;&nbsp;&nbsp;&nbsp; <a href="https://github.com/aashishchauhan06/logstash-config/pull/2/files">See detailed feedback -></a></li>
<li><b>Code change type</b>: NA</li>
<li><b>Unit tests added</b>: False</li>
<li><b>Estimated effort to review (1-5, lower is better)</b>: 2</li>
</ul>
</div>
<div>
<h3>High-level Feedback</h3>
Ensure thorough testing of the new configurations to prevent potential disruptions in production. Consider reviewing the impact of increased 'max_bytes' on system performance and stability.
</div>
<br>


<span text-align="top" margin="0 0 8px"><i>AI Code Review powered by</i></span>
<span tex-align="top"><sub>Bito Logo</sub></span>
</div>

**Comment by aashishchauhan06** [comment]
<div>
<h2>Code Review Agent Run #e4a38f</h2>
<div>
<ul>

</ul>
</div>
<div>
<h3>Code Review Overview</h3>
<ul>
<li><b>Summary</b>: The pull request introduces configuration changes in 'xml_config.conf', enhancing data handling and Elasticsearch setup for improved scalability.</li>
<li><b>Files</b>: 1</li>
<li><b>Issue found</b>: Total - 0, High importance - 0 &nbsp;&nbsp;&nbsp;&nbsp; <a href="https://github.com/aashishchauhan06/logstash-config/pull/2/files">See detailed feedback -></a></li>
<li><b>Code change type</b>: Configuration Changes</li>
<li><b>Unit tests added</b>: False</li>
<li><b>Estimated effort to review (1-5, lower is better)</b>: 2</li>
</ul>
</div>
<div>
<h3>High-level Feedback</h3>
Ensure thorough testing of the new configuration settings in 'xml_config.conf' to prevent potential disruptions. Consider adding rollback mechanisms for critical settings changes and monitor the system's performance closely following the updates.
</div>
<br>


<span text-align="top" margin="0 0 8px"><i>AI Code Review powered by</i></span>
<span tex-align="top"><sub>Bito Logo</sub></span>
</div>

**Pull request closed without merging**
